### ISSUE TITLE
rrbot_test_trajectory aborts without movement

### ISSUE THREAD

**Issue by lucasw** [davetcoleman/ros_control_boilerplate#18]
I've tried a few lunar and kinetic variations of 

    roslaunch ros_control_boilerplate rrbot_simulation.launch
    roslaunch ros_control_boilerplate rrbot_visualize.launch
    roslaunch ros_control_boilerplate rrbot_test_trajectory.launch

and so far none of them result in any motion on the arm.

Kinetic with latest github versions of ros_control, ros_controllers, ros_control_boilerplate, and gazebo_ros_demos

Lunar with deb ros_control and ros_controllers and github ros_control_boilerplate (it needs the improve_install fixes to be used here from the package manager) and gazebo_ros_demos

**Comment by lucasw** [comment]
Setting `sim_control_mode` to 0 (position instead of velocity) makes it work.

**Comment by PaulBouchier** [comment]
Thanks for the solution Lucas. I submitted pull request #19 to implement your solution.

**Comment by oPiZiL** [comment]
@lucasw  in  `rrbot_controllers.yaml` , that works.

**Comment by Shreeyak** [comment]
I faced this issue as well! Thanks @lucasw. 

@PaulBouchier Any update on that pull req? I saw it failed due to an eigen3 error?

**Comment by PaulBouchier** [comment]
@Shreeyak I didn't know it had failed - apparently you don't get email when a pull request fails. I can't imagine how the change I made would cause the failure to find Eigen3 in cmake. Seems like it might've gotten broken before somehow. I don't know how this CI stuff works or how to debug its problems.

**Comment by davetcoleman** [comment]
I have just merged it. Hopefully someone can address the Eigen issue separately. Please see how moveit_core links to Eigen3 for a good example. Thanks!

**Comment by Shreeyak** [comment]
Thank you for merging it!
