### ISSUE TITLE
Not able to use joint1_position_controller

### ISSUE THREAD

**Issue by saurabhbansal90** [davetcoleman/ros_control_boilerplate#31]
I did a build to this package, and was able to give the trajectory message and see it working.
I want to use `joint1_position_controller` also, and I added this controller in `ros_control_controller_manager` node in launch file `rrbot_simulation.launch`.

But it shows error, as below:

[ INFO] [1560239902.085325544]: Waiting for model URDF on the ROS param server at location: //rrbot/robot_description
[ INFO] [1560239902.189128348]: GenericHWInterface Ready.
[ INFO] [1560239902.189170636]: SimHWInterface Ready.
Loaded joint_state_controller
[ERROR] [1560239902.406392336]: Could not load class position_controllers/JointPositionController: Could not find library corresponding to plugin position_controllers/JointPositionController. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[ERROR] [1560239902.406551586]: Could not load controller 'joint1_position_controller' because controller type 'position_controllers/JointPositionController' does not exist.
[ERROR] [1560239902.406630563]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
Error when loading joint1_position_controller
Started ['joint_state_controller'] successfully
[ERROR] [1560239902.424348834]: Could not start controller with name joint1_position_controller because no controller with this name exists
Error when starting  ['joint1_position_controller']
[rrbot/ros_control_controller_manager-3] process has finished cleanly
log file: /home/saurabh/.ros/log/ae41ca82-8c1e-11e9-8d92-a86bad217c79/rrbot-ros_control_controller_manager-3*.log

**Comment by gavanderhoorn** [comment]
Do you actually have the `position_controllers` package installed?

**Comment by saurabhbansal90** [comment]
Hello gavanderhoorn, thanks the issue was same only, I didn't installed position_controllers.

I made my ros_controller, but here I am facing 1 issue, your write function from rrbot_hw_interface.cpp is only called when there is some update on the concerned topic.
But in my case, it is being repeatedly called. Any suggestion or clue on that?
Or do you need to see my implementation?

Or please let me know, if this is not a right platform.

Saurabh

**Comment by gavanderhoorn** [comment]
This is not my repository. You'll have to wait for someone from @PickNikRobotics to respond to your issue.

**Comment by saurabhbansal90** [comment]
@davetcoleman can you please some suggestion for this??

**Comment by davetcoleman** [comment]
>  I didn't installed position_controllers.

Was there a issue with the installation instructions? If so, please suggest a fix via PR

> your write function from rrbot_hw_interface.cpp is only called when there is some update on the concerned topic. But in my case, it is being repeatedly called. Any suggestion or clue on that?

I do not believe this is true. There is a control loop running at some hz in the [run()](https://github.com/PickNikRobotics/ros_control_boilerplate/blob/melodic-devel/src/generic_hw_control_loop.cpp#L67) function that is always writing commands.
