### ISSUE TITLE
Add .clang-format rules

### ISSUE THREAD

**Issue by RobertWilbrandt** [davetcoleman/ros_control_boilerplate#39]
I find it to be annoying to write cpp code without consistent auto formatting. Natural choices would be the moveit rules or [roscpp_code_format](https://github.com/davetcoleman/roscpp_code_format). Options would be:
- Copy one of the config files. Problem: I am not quite sure how this would all work with BSD3 copyright-notice, maybe someone knows this better.
- Create a custom config file.
- Just reference the moveit config in the README, moveit_ci can use this one when no .clang-format file exists. This would be pretty anoying, as you would have to pull it yourself when using it.

Any opinions?

**Comment by davetcoleman** [comment]
Surprisingly https://github.com/ros-controls/ros_control/ does not appear to be using clang-format!!

I made https://github.com/davetcoleman/roscpp_code_format but its a bit abandoned, and the MoveIt version is a more maintained one that forked off that original one. So +1 to using the MoveIt one (though they are very similar)

**Comment by RobertWilbrandt** [comment]
Done after merge of #47.
