### ISSUE TITLE
GenericHWControlLoop: use std::shared_ptr<hardware_interface::RobotHW> instead of boost

### ISSUE THREAD

**Issue by Tuebel** [davetcoleman/ros_control_boilerplate#43]
Is there any reason why `boost::shared_ptr` is used instead of the `std` version in `GenericHWControlLoop`?

**Comment by AndyZe** [comment]
Only because the repo was started before `std::shared_ptr` was available, I think. If you make a PR to update it, that would be great. I would approve it quickly.
