### ISSUE TITLE
compile the package issue with ROS Noetic 

### ISSUE THREAD

**Issue by TAZ010** [davetcoleman/ros_control_boilerplate#59]
I am facing an issue with using ros_control_boilerplate package, the latest package is supporting  Ros-Noetic, but when I compile the package using (Catkin Build)  it shows there is an error and you can see a picture of the error in the attachment.

If you can help me with this issue, I would be grateful.

**Comment by AndyZe** [comment]
It looks like there is no image attached. It's even better if you could copy/paste as text, though.

**Comment by TAZ010** [comment]
Sorry I forgot to add the photo, I attached the photo

![PastedGraphic-1](https://user-images.githubusercontent.com/108003477/175052375-1e10f55e-5b05-4436-9922-28a4a3b32d70.png)

**Comment by AndyZe** [comment]
You're going to have to try a little harder if you want help. That image is too small to read. Can you paste the error text, please?

**Comment by TAZ010** [comment]
sorry for that, this is my first time here in Github and I am not used to it.

this is the error

Errors     << ros_control_boilerplate:cmake /home/parallels/ws_moveit/logs/ros_control_boilerplate/build.cmake.027.log                 
CMake Error at /opt/ros/noetic/share/cmake_modules/cmake/Modules/FindGflags.cmake:50 (message):
  Could not find gflags library.
Call Stack (most recent call first):
  CMakeLists.txt:29 (find_package)


cd /home/parallels/ws_moveit/build/ros_control_boilerplate; catkin build --get-env ros_control_boilerplate | catkin env -si  /usr/bin/cmake /home/parallels/ws_moveit/src/ros_control_boilerplate --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/parallels/ws_moveit/devel/.private/ros_control_boilerplate -DCMAKE_INSTALL_PREFIX=/home/parallels/ws_moveit/install -DCMAKE_BUILD_TYPE=Release; cd -

.......................................................................................................................................
Failed     << ros_control_boilerplate:cmake                                  [ Exited with code 1 ]                                    
Failed    <<< ros_control_boilerplate                                        [ 1.3 seconds ]                                           
Abandoned <<< rosserial_mbed                                                 [ Unrelated job failed ]                                  
Abandoned <<< rosserial_embeddedlinux                                        [ Unrelated job failed ]                                  
Abandoned <<< rosserial_server                                               [ Unrelated job failed ]                                  
Abandoned <<< rosserial_tivac                                                [ Unrelated job failed ]                                  
Abandoned <<< rosserial_windows                                              [ Unrelated job failed ]                                  
Abandoned <<< srdfdom                                                        [ Unrelated job failed ]                                  
Abandoned <<< ur5_control                                                    [ Unrelated job failed ]                                  
Abandoned <<< ur5_urdf                                                       [ Unrelated job failed ]                                  
Abandoned <<< moveit                                                         [ Unrelated job failed ]                                  
Abandoned <<< moveit_planners                                                [ Unrelated job failed ]                                  
Abandoned <<< moveit_plugins                                                 [ Unrelated job failed ]                                  
Abandoned <<< moveit_commander                                               [ Unrelated job failed ]                                  
Abandoned <<< moveit_resources_prbt_moveit_config                            [ Unrelated job failed ]                                  
Abandoned <<< moveit_resources_prbt_pg70_support                             [ Unrelated job failed ]                                  
Abandoned <<< moveit_ros                                                     [ Unrelated job failed ]                                  
Abandoned <<< moveit_runtime                                                 [ Unrelated job failed ]                                  
Abandoned <<< panda_moveit_config                                            [ Unrelated job failed ]                                  
Abandoned <<< rosserial                                                      [ Unrelated job failed ]                                  
Abandoned <<< rosserial_arduino                                              [ Unrelated job failed ]                                  
Abandoned <<< rosserial_test                                                 [ Unrelated job failed ]                                  
Abandoned <<< rosserial_vex_cortex                                           [ Unrelated job failed ]                                  
Abandoned <<< rosserial_vex_v5                                               [ Unrelated job failed ]                                  
Abandoned <<< rosserial_xbee                                                 [ Unrelated job failed ]                                  
Abandoned <<< moveit_core                                                    [ Unrelated job failed ]                                  
Abandoned <<< chomp_motion_planner                                           [ Unrelated job failed ]                                  
Abandoned <<< moveit_chomp_optimizer_adapter                                 [ Unrelated job failed ]                                  
Abandoned <<< moveit_resources_prbt_ikfast_manipulator_plugin                [ Unrelated job failed ]                                  
Abandoned <<< moveit_ros_occupancy_map_monitor                               [ Unrelated job failed ]                                  
Abandoned <<< moveit_ros_planning                                            [ Unrelated job failed ]                                  
Abandoned <<< moveit_fake_controller_manager                                 [ Unrelated job failed ]                                  
Abandoned <<< moveit_kinematics                                              [ Unrelated job failed ]                                  
Abandoned <<< moveit_planners_ompl                                           [ Unrelated job failed ]                                  
Abandoned <<< moveit_ros_move_group                                          [ Unrelated job failed ]                                  
Abandoned <<< moveit_ros_manipulation                                        [ Unrelated job failed ]                                  
Abandoned <<< moveit_ros_perception                                          [ Unrelated job failed ]                                  
Abandoned <<< moveit_ros_robot_interaction                                   [ Unrelated job failed ]                                  
Abandoned <<< moveit_ros_warehouse                                           [ Unrelated job failed ]                                  
Abandoned <<< moveit_ros_benchmarks                                          [ Unrelated job failed ]                                  
Abandoned <<< moveit_ros_planning_interface                                  [ Unrelated job failed ]                                  
Abandoned <<< moveit_planners_chomp                                          [ Unrelated job failed ]                                  
Abandoned <<< moveit_ros_visualization                                       [ Unrelated job failed ]                                  
Abandoned <<< moveit_servo                                                   [ Unrelated job failed ]                                  
Abandoned <<< moveit_setup_assistant                                         [ Unrelated job failed ]                                  
Abandoned <<< moveit_simple_controller_manager                               [ Unrelated job failed ]                                  
Abandoned <<< moveit_ros_control_interface                                   [ Unrelated job failed ]                                  
Abandoned <<< moveit_visual_tools                                            [ Unrelated job failed ]                                  
Abandoned <<< moveit_tutorials                                               [ Unrelated job failed ]                                  
Abandoned <<< pilz_industrial_motion_planner_testutils                       [ Unrelated job failed ]                                  
Abandoned <<< pilz_industrial_motion_planner                                 [ Unrelated job failed ]                                  
Abandoned <<< ur5_new                                                        [ Unrelated job failed ]                                  
Finished  <<< rosserial_python                                               [ 0.2 seconds ]                                           
Finished  <<< rosserial_chibios                                              [ 0.2 seconds ]                                            
Finished  <<< rviz_visual_tools                                              [ 1.0 seconds ]                                            
[build] Summary: 18 of 69 packages succeeded.                                                                                           
[build]   Ignored:   None.                                                                                                              
[build]   Warnings:  None.                                                                                                              
[build]   Abandoned: 50 packages were abandoned.                                                                                        
[build]   Failed:    1 packages failed.                                                                                                 
[build] Runtime: 4.9 seconds total.                                    


Thank you for the help

**Comment by AndyZe** [comment]
That's a weird one. I'd try this:   https://stackoverflow.com/a/30650034

**Comment by TAZ010** [comment]
thank you

I tried the steps, but this is what shows 

----------------------------------------



`parallels@taz:~$` apt-cache search gflags
libgflags-dev - commandline flags module for C++ (development files)
libgflags-doc - documentation of gflags
libgflags2.2 - commandline flags module for C++ (shared library)
python3-gflags - implementation of the Google command line flags module - Python 3.x
ros-cmake-modules - Robot OS CMake Modules
parallels@taz:~$ sudo apt-get install libgflags2 libgflags-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libgflags2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libgflags2.2

E: Package 'libgflags2' has no installation candidate
parallels@taz:~$ 
` `

**Comment by AndyZe** [comment]
You may have to try some variations on that. libglags-dev or libgflags2.2 (on my system). You can use tab-complete to see what's available.  `sudo apt install libgflag(TAB)`

Of course, do `sudo apt update` before this

**Comment by TAZ010** [comment]
I tried the step, and now it works perfectly.

thank you very mucm
