### ISSUE TITLE
Ros2 support

### ISSUE THREAD

**Issue by IdoPractical** [davetcoleman/ros_control_boilerplate#62]
Hi,
Do you have any plans to port the package for Humble?
I'm trying to compile the package along with [hal_ros_control](https://github.com/zultron/hal_ros_control/tree/zultron/2023-04-14-humble-devel) but it fails because of the use of Catkin in the ros_control_boilerplate.
Thanks!

**Comment by JafarAbdi** [comment]
ros2_control has a built-in support for the same functionality, please take a look at https://control.ros.org/master/doc/ros2_control/hardware_interface/doc/mock_components_userdoc.html

**Comment by IdoPractical** [comment]
I will check it out.
Thank you!
